#!/usr/bin/env python3
"""Regenerate the embedded editor alpha glyphs (Pillow + fontTools, tooling only)."""
from pathlib import Path
import hashlib
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont
root = Path(__file__).resolve().parents[1]
source = root / 'res/editor-font/NotoSansMono-Regular.ttf'
font = ImageFont.truetype(str(source), 20)
codes = sorted(c for c in TTFont(source).getBestCmap() if c >= 32)
data, records = [], []
for code in codes:
    img = Image.new('L', (16, 32))
    ImageDraw.Draw(img).text((2, 24), chr(code), font=font, fill=255, anchor='ls')
    pixels = list(img.tobytes())
    offset = len(data)
    for value in pixels:
        if len(data) > offset and data[-1] == value and data[-2] < 255:
            data[-2] += 1
        else:
            data.extend((1, value))
    records.append((code, offset))
lines = ['// Generated by tools/build-editor-font.py. Font data: SIL OFL 1.1; see EDITOR-FONT-LICENSE.txt.',
         '// Source SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
         'struct FontGlyph {uint32_t code,offset;};', 'static constexpr FontGlyph fontGlyphs[]={']
lines += [f'{{{c},{o}}},' for c,o in records]
lines += ['};', 'static constexpr uint8_t fontAlpha[]={']
lines += [','.join(str(v) for v in data[i:i+32])+',' for i in range(0,len(data),32)]
lines += ['};']
(root / 'src/cartographer/fontdata.inc').write_text('\n'.join(lines)+'\n')
print(len(records), 'glyphs;',len(data),'RLE bytes')
