#!/usr/bin/env python3
"""Regenerate tools/ctest_costs.txt from a build dir's ctest timings.

  tools/ctest_costs.py BUILD_DIR [--threshold SECONDS] [--merge OTHER_COSTS ...]

Run the full suite once first (ctest --test-dir BUILD_DIR -j 8); ctest writes each
test's wall time to BUILD_DIR/Testing/Temporary/CTestCostData.txt. Tests at or above
the threshold (default 5 s) are listed longest first; CMakeLists.txt turns the list
into COST properties (long tests start first) and gives every test NOT in it, and not
labelled nightly, the `quick` label. Times are rounded to whole seconds, so the file
changes only when a test really moves. --merge takes the larger time per test from
other cost files (e.g. one measured on a different host).
"""
import argparse
import sys
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("build_dir")
parser.add_argument("--threshold", type=float, default=5.0)
parser.add_argument("--merge", nargs="*", default=[])
args = parser.parse_args()

cost = {}


def read(path, ctest_format):
    for line in Path(path).read_text().splitlines():
        parts = line.split()
        if ctest_format:
            if len(parts) == 3 and parts[0] != "---":
                cost[parts[0]] = max(cost.get(parts[0], 0.0), float(parts[2]))
        elif len(parts) >= 2 and not line.startswith("#"):
            cost[parts[0]] = max(cost.get(parts[0], 0.0), float(parts[1]))


data = Path(args.build_dir) / "Testing" / "Temporary" / "CTestCostData.txt"
if not data.exists():
    sys.exit(f"{data}: not found; run ctest in {args.build_dir} first")
read(data, True)
for other in args.merge:
    read(other, False)
rows = sorted(((round(t), n) for n, t in cost.items() if t >= args.threshold), key=lambda r: (-r[0], r[1]))
out = Path(__file__).with_name("ctest_costs.txt")
out.write_text("# <test> <seconds>: tests of 5 s or more, longest first. Generated by tools/ctest_costs.py;\n"
               "# CMakeLists.txt turns this into COST properties and the `quick` label (all other non-nightly tests).\n"
               + "".join(f"{n} {t}\n" for t, n in rows))
print(f"{out}: {len(rows)} tests >= {args.threshold:g} s")
