# Use the target architecture, never the build host, for package metadata/names.
function(tak_linux_package_architecture processor deb_out rpm_out)
  string(TOLOWER "${processor}" processor)
  if(processor MATCHES "^(aarch64|arm64)$")
    set(deb arm64)
    set(rpm aarch64)
  elseif(processor MATCHES "^(x86_64|amd64)$")
    set(deb amd64)
    set(rpm x86_64)
  else()
    message(FATAL_ERROR "Unsupported Linux package architecture: ${processor}")
  endif()
  set(${deb_out} "${deb}" PARENT_SCOPE)
  set(${rpm_out} "${rpm}" PARENT_SCOPE)
endfunction()
